services:
  # -----------------------------------------------
  # 1. База данных PostgreSQL 15
  # -----------------------------------------------
  db:
    ports:
      - "127.0.0.1:5432:5432"
    image: postgres:15-alpine
    container_name: tec_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tec_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD не задан в .env}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # -----------------------------------------------
  # 2. Бэкенд C# (.NET)
  # -----------------------------------------------
  tec_api:
    build:
      context: ./tecAPI # Контекст — верхняя папка tecAPI
      dockerfile: tecBackend/Dockerfile # Путь к Dockerfile внутри tecBackend
    container_name: tec_api_app
    restart: unless-stopped
    env_file:
      - ./tecAPI/tecBackend/.env # Путь к .env бэкенда
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB:-tec_db};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD не задан в .env}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  # -----------------------------------------------
  # 3. Фронтенд Next.js
  # -----------------------------------------------
  tec_client:
    build:
      context: ./tec_client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://btec.kg/api-backend
        API_URL: http://tec_api:8080/api
    container_name: tec_client_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://btec.kg/api-backend
      - API_URL=http://tec_api:8080/api
    depends_on:
      - tec_api

  # -----------------------------------------------
  # 4. Reverse Proxy Nginx
  # -----------------------------------------------
  nginx:
    image: nginx:alpine
    container_name: tec_nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - tec_client
      - tec_api

volumes:
  postgres_data: