// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tecBackend.Models;

#nullable disable

namespace tecBackend.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20260928034928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tecBackend.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Department", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<short?>("Amount")
                        .HasColumnType("smallint")
                        .HasColumnName("amount");

                    b.Property<short>("Archive")
                        .HasColumnType("smallint")
                        .HasColumnName("archive");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("CommentReshenie")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("comment_reshenie");

                    b.Property<DateTime>("DateFirst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_first")
                        .HasDefaultValueSql("'0001-01-01 00:00:00'");

                    b.Property<DateTime?>("DateReshenie")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_reshenie");

                    b.Property<DateTime?>("DateVyp")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_vyp");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<int>("IdPerUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_per_user");

                    b.Property<string>("IdReceiver")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("id_receiver");

                    b.Property<int>("IdResource")
                        .HasColumnType("integer")
                        .HasColumnName("id_resource");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("id_user");

                    b.Property<short>("Made")
                        .HasColumnType("smallint")
                        .HasColumnName("made");

                    b.Property<string>("UserReshenie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("user_reshenie")
                        .HasComment("Пользователь, который разрешил/отклонил заявку");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Otdel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDep")
                        .HasColumnType("integer")
                        .HasColumnName("id_dep");

                    b.Property<short>("IdOtd")
                        .HasColumnType("smallint")
                        .HasColumnName("id_otd");

                    b.Property<short?>("IdOtdBuhgalter")
                        .HasColumnType("smallint")
                        .HasColumnName("idotd_buhgalter");

                    b.Property<string>("NameOtd")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name_otd")
                        .HasDefaultValueSql("''");

                    b.HasKey("Id");

                    b.ToTable("otdel", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("CreatorDepartment")
                        .HasColumnType("text")
                        .HasColumnName("creatordepartment");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text")
                        .HasColumnName("creatorname");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("news_posts_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("news_posts", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Resource", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("IdOtd")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("id_otd")
                        .HasComment("Код отдела, который исполняет эту заявку");

                    b.Property<short?>("IdParent")
                        .HasColumnType("smallint")
                        .HasColumnName("id_parent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Priznak")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("priznak")
                        .HasComment("1=замена, 2=установка");

                    b.HasKey("Id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<short>("Ban")
                        .HasColumnType("smallint")
                        .HasColumnName("ban");

                    b.Property<short>("BanAmount")
                        .HasColumnType("smallint")
                        .HasColumnName("ban_amount");

                    b.Property<string>("BanComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ban_comment");

                    b.Property<DateTime?>("BanDate")
                        .HasColumnType("date")
                        .HasColumnName("ban_date");

                    b.Property<DateTime?>("ComeDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("comedate")
                        .HasComment("время и дата загрузки чата");

                    b.Property<short?>("IdGroup")
                        .HasColumnType("smallint")
                        .HasColumnName("id_group");

                    b.Property<short>("IdPost")
                        .HasColumnType("smallint")
                        .HasColumnName("id_post");

                    b.Property<string>("Login")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("login")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Mail")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mail");

                    b.Property<int?>("OtdelId")
                        .HasColumnType("integer")
                        .HasColumnName("otdelid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Tabel")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tabel");

                    b.HasKey("Id");

                    b.HasIndex("OtdelId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expirytime");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("tecBackend.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DatePriem")
                        .HasColumnType("date")
                        .HasColumnName("datepriem");

                    b.Property<string>("Doljnost")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doljnost");

                    b.Property<DateTime>("Dr")
                        .HasColumnType("date")
                        .HasColumnName("dr");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fio");

                    b.Property<string>("Ids")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("ids");

                    b.Property<string>("KategoriyaId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("kategoriyaid")
                        .HasComment("категория работника (начальники/мастера и т.д.)");

                    b.Property<string>("KategoriyaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kategoriyaname")
                        .HasComment("наименование категории работника");

                    b.Property<string>("Otdel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdel")
                        .HasComment("отдел рус.полностью");

                    b.Property<string>("OtdelId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otdelid");

                    b.Property<string>("OtdelKyrB")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdelkyrb")
                        .HasComment("отдел кирг. полностью");

                    b.Property<string>("OtdelKyrS")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdelkyrs")
                        .HasComment("отдел кирг.кратко");

                    b.Property<string>("OtdelRusS")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdelruss")
                        .HasComment("отдел рус. кратко");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("phone");

                    b.Property<string>("Tabel")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tabel");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique();

                    b.ToTable("workers", null, t =>
                        {
                            t.HasComment("Справочник сотрудников");
                        });
                });

            modelBuilder.Entity("tecBackend.Models.Workers18062024", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DatePriem")
                        .HasColumnType("date")
                        .HasColumnName("datePriem");

                    b.Property<string>("Doljnost")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doljnost");

                    b.Property<DateTime>("Dr")
                        .HasColumnType("date")
                        .HasColumnName("DR");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FIO");

                    b.Property<string>("Ids")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("IDs");

                    b.Property<string>("KategoriyaId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("kategoriyaID")
                        .HasComment("категория работника (начальники/мастера и т.д.)");

                    b.Property<string>("KategoriyaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kategoriyaName")
                        .HasComment("наименование категории работника");

                    b.Property<string>("Otdel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdel");

                    b.Property<string>("OtdelId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otdelID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("phone");

                    b.Property<string>("Tabel")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("TABEL");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id1");

                    b.ToTable("workers18-06-2024", null, t =>
                        {
                            t.HasComment("Справочник сотрудников");
                        });
                });

            modelBuilder.Entity("tecBackend.Models.Workers1otdel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DatePriem")
                        .HasColumnType("date")
                        .HasColumnName("datePriem");

                    b.Property<string>("Doljnost")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doljnost");

                    b.Property<DateTime>("Dr")
                        .HasColumnType("date")
                        .HasColumnName("DR");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FIO");

                    b.Property<string>("Ids")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("IDs");

                    b.Property<string>("KategoriyaId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("kategoriyaID")
                        .HasComment("категория работника (начальники/мастера и т.д.)");

                    b.Property<string>("KategoriyaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kategoriyaName")
                        .HasComment("наименование категории работника");

                    b.Property<string>("Otdel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdel")
                        .HasComment("отдел рус.полностью");

                    b.Property<string>("OtdelId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otdelID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("phone");

                    b.Property<string>("Tabel")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("TABEL");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id2");

                    b.ToTable("workers_1otdel", null, t =>
                        {
                            t.HasComment("Справочник сотрудников");
                        });
                });

            modelBuilder.Entity("tecBackend.Models.WorkersCopy", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DatePriem")
                        .HasColumnType("date")
                        .HasColumnName("datePriem");

                    b.Property<string>("Doljnost")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doljnost");

                    b.Property<DateTime>("Dr")
                        .HasColumnType("date")
                        .HasColumnName("DR");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FIO");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Ids")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("IDs");

                    b.Property<string>("KategoriyaId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("kategoriyaID")
                        .HasComment("категория работника (начальники/мастера и т.д.)");

                    b.Property<string>("Mphone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mphone");

                    b.Property<string>("Otdel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdel");

                    b.Property<string>("OtdelId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otdelID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Tabel")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("TABEL");

                    b.ToTable("workers_copy", null, t =>
                        {
                            t.HasComment("Справочник сотрудников");
                        });
                });

            modelBuilder.Entity("tecBackend.Models.WorkersEmpty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DatePriem")
                        .HasColumnType("date")
                        .HasColumnName("datePriem");

                    b.Property<string>("Doljnost")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doljnost");

                    b.Property<DateTime>("Dr")
                        .HasColumnType("date")
                        .HasColumnName("DR");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FIO");

                    b.Property<string>("Ids")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("IDs");

                    b.Property<string>("KategoriyaId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("kategoriyaID")
                        .HasComment("категория работника (начальники/мастера и т.д.)");

                    b.Property<string>("KategoriyaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kategoriyaName");

                    b.Property<string>("Mphone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mphone");

                    b.Property<string>("Otdel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("otdel");

                    b.Property<string>("OtdelId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otdelID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Tabel")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("TABEL");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id3");

                    b.ToTable("workers_empty", null, t =>
                        {
                            t.HasComment("Справочник сотрудников");
                        });
                });

            modelBuilder.Entity("tecBackend.Models.Zayavkatmc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("action")
                        .HasComment("действие: 0-новая,1-прочитанная,2-выполненная,3-отложенная,4-отказная");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp")
                        .HasColumnName("dateAction")
                        .HasComment("дата разрешения заявки");

                    b.Property<string>("IdDep")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("id_dep");

                    b.Property<string>("IdOborud")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("idOborud");

                    b.Property<string>("IdWork")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("idWork");

                    b.Property<string>("Kvartal")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("kvartal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("name");

                    b.Property<string>("Rem")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("rem");

                    b.Property<string>("Sposob")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sposob");

                    b.HasKey("Id");

                    b.ToTable("zayavkatmc", (string)null);
                });

            modelBuilder.Entity("tecBackend.Models.Post", b =>
                {
                    b.HasOne("tecBackend.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tecBackend.Models.User", b =>
                {
                    b.HasOne("tecBackend.Models.Otdel", "Otdel")
                        .WithMany()
                        .HasForeignKey("OtdelId");

                    b.Navigation("Otdel");
                });

            modelBuilder.Entity("tecBackend.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
